server:
  port: 20190
spring:
  application:
    name: config
  profiles:
    active: dev

---

spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://192.168.9.231/suwenguang/cloud-config.git
          username: suwenguang
          password: suwenguang
          basedir: /data/config/cloud
          skip-ssl-validation: true
          default-label: master
    stream:
      kafka:
        binder:
          brokers: http://192.168.9.233:9092
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20201/eureka/
  instance:
    hostname: localhost
logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/config/info.config.log


---

spring:
  profiles: test
  cloud:
    config:
      server:
        git:
          uri: https://192.168.9.231/suwenguang/cloud-config.git
          username: suwenguang
          password: suwenguang
          basedir: /data/config/cloud
          skip-ssl-validation: true
          default-label: master
    stream:
      kafka:
        binder:
          brokers: http://192.168.9.233:9092
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://192.168.9.239:20201/eureka/
  instance:
    hostname: 192.168.9.233
logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/config/info.config.log

---

spring:
  profiles: pro
  cloud:
    config:
      server:
        git:
          uri: https://192.168.9.231/suwenguang/cloud-config.git
          username: suwenguang
          password: suwenguang
          basedir: /data/config/cloud
          skip-ssl-validation: true
          default-label: master
    stream:
      kafka:
        binder:
          brokers: http://192.168.9.233:9092
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://192.168.9.239:20201/eureka/
  instance:
    hostname: 192.168.9.233
logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/config/info.config.log
