env: dev
version: 1.0.0
server:
  port: 19197
spring:
  application:
    name: config
  cloud:
      config:
          server:
              git:
                  uri: https://192.168.9.231/suwenguang/cloud-config.git
                  username: suwenguang
                  password: suwenguang
                  basedir: /data/config/cloud
#todo://服务暴露: 线上修改
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19191/eureka/
logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/config/info.config.log
