env: dev
version: 0.0.2
server:
  port: 20190
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://192.168.9.231/suwenguang/cloud-config.git
          username: suwenguang
          password: suwenguang
          basedir: /data/config/cloud
          skip-ssl-validation: true
          default-label: master
    stream:
      kafka:
        binder:
          brokers: http://127.0.0.1:9092
#todo://服务暴露: 线上修改
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20200/eureka/
logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/config/info.config.log
