server:
  port: 30105
  servlet:
    context-path: /user
  compression:
    mime-types: text/xml,application/xml,application/json
    min-response-size: 2048

feign:
  client:
    config: # 这里配置feign全局配置
      connectTimeout: 5000
      readTimeout: 5000
      loggerLevel: full
  httpclient:
    disable-ssl-validation: true
# To disable Hystrix in Feign
  hystrix:
    enabled: false
  compression:
    request:
      enabled: true
    response:
      enabled: true
