variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - ./.m2/repository
# 定义 stages
stages:
  - build
  - backup
  - deploy
  - cleanup

# 定义 job
build-job:
  stage: build
  script:
    - source /etc/profile
    - source ~/.bashrc
    - mvn clean package -Dmaven.test.skip=true
    - "ls -thr"
  artifacts:
    paths:
      - "*/target/*.war"

#backup-job:
#  stage: backup
#  script:
#    - "ls -thr"
#    - 'cd server/target'
#    - 'mv  *.war /data/files/ttCommision.server.war'
#    - 'cd ../../task/target'
#    - 'mv *.war /data/files/ttCommision.task.war'
#    - 'cp -rf /data/server/resin-pro-4.0.43/webapps/ttCommision/ /data/server/resin-pro-4.0.43/backup/ttCommision-$(date "+%Y-%m-%d")'
#    - 'cp -rf /data/server/resin-pro-4.0.43/webapps/ttc-task/ /data/server/resin-pro-4.0.43/backup/ttc-task-$(date "+%Y-%m-%d")'
#
#deploy-job:
#  stage: deploy
#  except:
#    changes:
#      - "*.md"
#  script:
#    - 'rm -rf /data/server/resin-pro-4.0.43/webapps/ttCommision'
#    - 'unzip  /data/files/ttCommision.server.war -d /data/server/resin-pro-4.0.43/webapps/ttCommision'
#    - 'rm -rf /data/server/resin-pro-4.0.43/webapps/ttc-task'
#    - 'unzip  /data/files/ttCommision.task.war -d /data/server/resin-pro-4.0.43/webapps/ttc-task'
#    - '/data/server/resin-pro-4.0.43/bin/resin.sh   restart'

