spring:
  cloud:
    consul:
      host: 192.168.9.233
      port: 18500
      discovery:
        service-name: order-service #注册在consul上面的名字，在consul的调用中，是通过此名字调用的
        register-health-check: true #健康检查，保证服务处于启动状态，建议开启
#服务调用配置
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/info.order.log
