server:
  port: 19192
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19191/eureka/

zuul:
  prefix: /cloud
  routes:
    sponsor:
      path: /user/**
      serviceId: eureka-service-user
      strip-prefix: false
  add-host-header: true
  add-proxy-headers: true
