server:
  port: 19192
spring:
  application:
    name: gateway
#todo://服务暴露: 线上修改
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19191/eureka/

zuul:
  #  prefix: /cloud
  #配置路由
  routes:
    #用户服务
    user:
      #拦截路径
      path: /user/**
      #服务id,根据application.yml配置
      serviceId: user
      #是否分割网关路由的路径,默认true
      #无prefix时
      #当strip-prefix=true的时候 （http://localhost:5016/user-service/1 -> http://localhost:4011/1)
      #当strip-prefix=false的时候（http://localhost:5016/user-service/1 -> http://localhost:4011/user-service/1）
      strip-prefix: false
    #后台服务
    console:
      #拦截路径
      path: /console/**
      #服务id,根据application.yml配置
      serviceId: console
      #是否分割网关路由的路径,默认true
      #无prefix时
      #当strip-prefix=true的时候 （http://localhost:5016/user-service/1 -> http://localhost:4011/1)
      #当strip-prefix=false的时候（http://localhost:5016/user-service/1 -> http://localhost:4011/user-service/1）
      strip-prefix: false
    #订单服务
    order:
      #拦截路径
      path: /order/**
      #服务id,根据application.yml配置
      serviceId: order
      strip-prefix: false
  #重定向问题
  add-host-header: true
  #标记，用来判断proxy是否应该添加X-Forwarded-* headers
  add-proxy-headers: true
  debug:
    request: true
logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/gateway/info.gateway.log
  level:
    com.netflix: DEBUG
