zuul:
  routes:
    console:
      path: /console/**
      serviceId: console-service
      strip-prefix: false
    order:
      path: /order/**
      serviceId: order-service
      strip-prefix: false
  add-host-header: true
  add-proxy-headers: true
env:
  version: 1.0
  author: suveng
