spring:
  profiles:
    active: dev
  cloud:
    consul:
      host: 192.168.9.233
      port: 18500
      discovery:
        service-name: zuul #注册在consul上面的名字，在consul的调用中，是通过此名字调用的
        register-health-check: true #健康检查，保证服务处于启动状态，建议开启
#服务暴露: 线上修改
management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  #  prefix: /cloud
  #配置路由
  routes:
    #后台服务
    console:
      #拦截路径
      path: /console/**
      #服务id,根据application.yml配置
      serviceId: console-service
      #是否分割网关路由的路径,默认true
      #无prefix时
      #当strip-prefix=true的时候 （http://localhost:5016/user-service/1 -> http://localhost:4011/1)
      #当strip-prefix=false的时候（http://localhost:5016/user-service/1 -> http://localhost:4011/user-service/1）
      strip-prefix: false
    #订单服务
    order:
      #拦截路径
      path: /order/**
      #服务id,根据application.yml配置
      serviceId: order-service
      strip-prefix: false
  #重定向问题
  add-host-header: true
  #标记，用来判断proxy是否应该添加X-Forwarded-* headers
  add-proxy-headers: true

logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/gateway/info.gateway.log

