spring:
  profiles:
    active: dev
  application:
    name: eureka

---
spring:
  profiles: dev
server:
  port: 20201
eureka:
  instance:
    hostname: localhost
  client:
    # eureka.client.fetch-registry: 表示是否从 Eureka Server 获取注册信息，默认为true。如果这是一个单点的 Eureka Server，不需要同步其他节点的数据，设为false
    fetch-registry: false
    # eureka.client.register-with-eureka: 表示是否将自己注册到 Eureka Server, 默认为true。由于当前应用就是 Eureka Server, 因此设为 false
    register-with-eureka: false
    # 设置 Eureka Server 所在的地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://localhost:20201/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/eureka/info.eureka.log

---
spring:
  profiles: test
server:
  port: 20201

eureka:
  instance:
    hostname: 192.168.9.232
  client:
    # eureka.client.fetch-registry: 表示是否从 Eureka Server 获取注册信息，默认为true。如果这是一个单点的 Eureka Server，不需要同步其他节点的数据，设为false
    fetch-registry: true
    # eureka.client.register-with-eureka: 表示是否将自己注册到 Eureka Server, 默认为true。由于当前应用就是 Eureka Server, 因此设为 false
    register-with-eureka: true
    # 设置 Eureka Server 所在的地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://192.168.9.232:20201/eureka/,http://192.168.9.239:20201/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 400
#todo://服务暴露: 线上修改
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/eureka/info.eureka.log

---
spring:
  profiles: pro
server:
  port: 20201

eureka:
  instance:
    hostname: 192.168.9.232
  client:
    # eureka.client.fetch-registry: 表示是否从 Eureka Server 获取注册信息，默认为true。如果这是一个单点的 Eureka Server，不需要同步其他节点的数据，设为false
    fetch-registry: true
    # eureka.client.register-with-eureka: 表示是否将自己注册到 Eureka Server, 默认为true。由于当前应用就是 Eureka Server, 因此设为 false
    register-with-eureka: true
    # 设置 Eureka Server 所在的地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://192.168.9.232:20201/eureka/,http://192.168.9.239:20201/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 400
#todo://服务暴露: 线上修改
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/eureka/info.eureka.log
