env: dev

version: 1.0.0

spring:
  application:
    name: admin
server:
  port: 20201

#服务注册配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19191/eureka/
      
#服务调用配置
feign:
  hystrix:
    enabled: true
    
#todo://服务暴露: 线上修改
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/admin/info.admin.log
