spring:
  application:
    name: admin
  profiles:
    active: dev


---
spring:
  profiles: dev

server:
  port: 20220

#服务注册配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20201/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/admin/info.admin.log

---
spring:
  profiles: test

server:
  port: 20220

#服务注册配置
eureka:
  client:
    service-url:
      defaultZone: http://192.168.9.239:20201/eureka/
  instance:
    hostname: 192.168.9.233

#todo://服务暴露: 线上修改
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/admin/info.admin.log
  
---
spring:
  profiles: pro

server:
  port: 20220

#服务注册配置
eureka:
  client:
    service-url:
      defaultZone: http://192.168.9.239:20201/eureka/
  instance:
    hostname: 192.168.9.233

#todo://服务暴露: 线上修改
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  config: classpath:logback-spring.xml
  file: /data/log/cloud/admin/info.admin.log
