#服务配置
server:
  #服务端口
  port: 19195
  #服务入口前缀
  servlet:
    context-path: /console
#spring的配置
spring:
  #spring应用配置
  application:
    #应用名称
    name: console-service
  #数据源配置
  datasource:
    druid:
      
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 最大连接池数量
      max-active: 30
      # 最小连接池数量
      min-idle: 5
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50
      # 合并多个DruidDataSource的监控数据
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      use-global-data-source-stat: true
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 500
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://111.230.95.206:3306/system?autoReconnect=true&characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
      username: root
      password: zxcvbnm123...
    #tomcat容器配置
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  #视图引擎配置
  freemarker:
    #视图存放目录
    template-loader-path: classpath:/templates/
    #缓存启动配置
    cache: false
    charset: utf-8
    allow-request-override: false
    allow-session-override: false
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    #在 ftl 中使用 request.contextPath
    request-context-attribute: request
    settings: {"date_format":"yyyy-MM-dd","datetime_format":"yyyy-MM-dd HH:mm:ss"}
    suffix: .ftl
#服务注册配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19191/eureka/
#服务调用配置
feign:
  hystrix:
    enabled: true
#服务暴露
management:
  endpoints:
    web:
      exposure:
        include: "*"


