env:
  version: 1.5-gateway
  author: suveng
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: test-user-provider
          uri: lb://test-user-provider-service
          predicates:
            - Path=/user/**
